export type Subject = "math" | "physics" | "chemistry";
export type Stage = "primary" | "junior" | "senior";

export interface ParamDef {
  key: string;
  label: string;
  min: number;
  max: number;
  step: number;
  default: number;
  unit?: string;
}

export interface Topic {
  id: string;
  subject: Subject;
  stage: Stage;
  group: string;
  title: string;
  formula: string;
  description: string;
  params: ParamDef[];
  componentKey: string;
  steps?: string[];
  hint?: string;
  animated?: boolean;
  animationDuration?: number;
}

export const SUBJECT_LABELS: Record<Subject, string> = {
  math: "数学",
  physics: "物理",
  chemistry: "化学",
};

export const STAGE_LABELS: Record<Stage, string> = {
  primary: "小学",
  junior: "初中",
  senior: "高中",
};

export const STAGES: Stage[] = ["primary", "junior", "senior"];
export const SUBJECTS: Subject[] = ["math", "physics", "chemistry"];

export const TOPICS: Topic[] = [
  {
    id: "linear-function",
    subject: "math",
    stage: "junior",
    group: "函数与图像",
    title: "一次函数",
    formula: "y = kx + b",
    description: "调节斜率 k 与截距 b，观察直线的旋转与平移。",
    params: [
      { key: "k", label: "k 斜率", min: -5, max: 5, step: 0.1, default: 1 },
      { key: "b", label: "b 截距", min: -10, max: 10, step: 0.5, default: 0 },
    ],
    componentKey: "linear-function",
    steps: ["设定 k 与 b", "代入两个 x 取值", "连成直线", "分析斜率含义"],
    hint: "当 k > 0 时，y 随 x 增大而增大；k = 0 时退化为水平直线。",
  },
  {
    id: "quadratic",
    subject: "math",
    stage: "junior",
    group: "函数与图像",
    title: "二次函数",
    formula: "y = ax² + bx + c",
    description: "调节 a、b、c，观察抛物线开口与顶点位置。",
    params: [
      { key: "a", label: "a", min: -3, max: 3, step: 0.1, default: 1 },
      { key: "b", label: "b", min: -6, max: 6, step: 0.1, default: 0 },
      { key: "c", label: "c", min: -10, max: 10, step: 0.5, default: 0 },
    ],
    componentKey: "quadratic",
    steps: ["观察抛物线形状", "找对称轴 x = -b/(2a)", "计算顶点", "分析开口方向"],
    hint: "a > 0 开口向上，a < 0 开口向下；|a| 越大开口越窄。",
    animated: true,
    animationDuration: 5,
  },
  {
    id: "sequence-limit",
    subject: "math",
    stage: "senior",
    group: "极限与数列",
    title: "数列极限",
    formula: "aₙ = 1 / n",
    description: "演示 n 增大时数列项收敛到 0 的过程。",
    params: [
      { key: "N", label: "N 项数", min: 5, max: 200, step: 1, default: 40 },
    ],
    componentKey: "sequence-limit",
    steps: ["计算各 aₙ", "绘制散点", "观察是否趋于 0", "形式化定义"],
    hint: "ε–N 语言：∀ε>0, ∃N, ∀n>N, |aₙ| < ε。",
  },
  {
    id: "free-fall",
    subject: "physics",
    stage: "junior",
    group: "力学",
    title: "自由落体",
    formula: "h = ½ g t²",
    description: "物体从高度 h 自由下落，实时显示位移与速度。",
    params: [
      { key: "h", label: "初始高度 h", min: 1, max: 50, step: 1, default: 20, unit: "m" },
      { key: "g", label: "重力加速度 g", min: 1.6, max: 25, step: 0.1, default: 9.8, unit: "m/s²" },
    ],
    componentKey: "free-fall",
    steps: ["初始 v=0", "v = gt", "y = h - ½gt²", "落地时间 t = √(2h/g)"],
    hint: "落地速度 v = √(2gh)，与质量无关。",
    animated: true,
    animationDuration: 10,
  },
  {
    id: "projectile",
    subject: "physics",
    stage: "senior",
    group: "运动学",
    title: "抛体运动",
    formula: "x = v₀cosθ·t,  y = v₀sinθ·t − ½gt²",
    description: "调节初速度、角度，观察抛物线轨迹与射程。",
    params: [
      { key: "v0", label: "初速度 v₀", min: 5, max: 60, step: 1, default: 25, unit: "m/s" },
      { key: "angle", label: "发射角 θ", min: 5, max: 85, step: 1, default: 45, unit: "°" },
      { key: "g", label: "g", min: 1.6, max: 25, step: 0.1, default: 9.8, unit: "m/s²" },
    ],
    componentKey: "projectile",
    steps: ["分解水平与竖直速度", "水平匀速 / 竖直匀变速", "求落地时间", "代入射程"],
    hint: "理想条件下 45° 时射程最大。",
    animated: true,
    animationDuration: 10,
  },
  {
    id: "rlc",
    subject: "physics",
    stage: "senior",
    group: "电学",
    title: "RLC 串联谐振",
    formula: "f₀ = 1 / (2π√LC)",
    description: "调节 R、L、C、频率 f，观察电流幅值随频率的变化。",
    params: [
      { key: "R", label: "R", min: 1, max: 100, step: 1, default: 10, unit: "Ω" },
      { key: "L", label: "L", min: 0.01, max: 1, step: 0.01, default: 0.1, unit: "H" },
      { key: "C", label: "C (μF)", min: 1, max: 200, step: 1, default: 50, unit: "μF" },
      { key: "f", label: "驱动频率 f", min: 10, max: 500, step: 1, default: 70, unit: "Hz" },
    ],
    componentKey: "rlc",
    steps: ["计算 X_L = 2πfL", "计算 X_C = 1/(2πfC)", "阻抗 Z = √(R²+(X_L−X_C)²)", "I = U/Z"],
    hint: "谐振发生在 X_L = X_C，电流达到最大。",
  },
  {
    id: "solubility",
    subject: "chemistry",
    stage: "junior",
    group: "溶液",
    title: "溶解度曲线",
    formula: "S = f(T)",
    description: "温度升高时多数固体溶解度增大，气体溶解度减小。",
    params: [
      { key: "T", label: "温度 T", min: 0, max: 100, step: 1, default: 40, unit: "°C" },
      { key: "substance", label: "物质 (0:KNO₃ 1:NaCl 2:Ca(OH)₂)", min: 0, max: 2, step: 1, default: 0 },
    ],
    componentKey: "solubility",
    steps: ["选定物质", "查温度对应溶解度", "判断饱和/不饱和", "结晶分析"],
    hint: "Ca(OH)₂ 是反例：溶解度随温度升高而下降。",
  },
  {
    id: "equilibrium",
    subject: "chemistry",
    stage: "senior",
    group: "反应原理",
    title: "化学平衡 A + B ⇌ C",
    formula: "K = [C] / ([A][B])",
    description: "模拟可逆反应浓度随时间变化，最终达到平衡。",
    params: [
      { key: "A0", label: "[A]₀", min: 0.1, max: 3, step: 0.1, default: 1, unit: "mol/L" },
      { key: "B0", label: "[B]₀", min: 0.1, max: 3, step: 0.1, default: 1, unit: "mol/L" },
      { key: "K", label: "平衡常数 K", min: 0.1, max: 10, step: 0.1, default: 2 },
    ],
    componentKey: "equilibrium",
    steps: ["写正逆反应速率", "联立求解平衡浓度", "勒夏特列原理", "改变 K 观察移动"],
    hint: "升温使吸热方向有利；增大反应物浓度，平衡正向移动。",
    animated: true,
    animationDuration: 8,
  },
  {
    id: "isomer",
    subject: "chemistry",
    stage: "senior",
    group: "有机化学",
    title: "丁烷异构体",
    formula: "C₄H₁₀",
    description: "切换正丁烷与异丁烷，观察碳骨架差异。",
    params: [
      { key: "type", label: "异构体类型", min: 0, max: 1, step: 1, default: 0, unit: "0=正丁烷 1=异丁烷" },
    ],
    componentKey: "isomer",
    steps: ["写出分子式", "枚举碳骨架", "命名", "比较物理性质"],
    hint: "同分异构体：分子式相同，结构不同，性质有差异。",
  },
  {
    id: "linear-equation",
    subject: "math",
    stage: "junior",
    group: "方程与不等式",
    title: "一元一次方程",
    formula: "ax + b = 0",
    description: "通过数轴可视化，理解移项、除法求解一元一次方程的过程。",
    params: [
      { key: "a", label: "a 系数", min: -5, max: 5, step: 0.1, default: 2 },
      { key: "b", label: "b 常数", min: -10, max: 10, step: 0.5, default: -4 },
    ],
    componentKey: "linear-equation",
    steps: ["写出方程 ax+b=0", "移项: ax = -b", "两边除以 a", "x = -b/a"],
    hint: "a 不能为 0；移项时注意变号。",
  },
  {
    id: "accelerated-motion",
    subject: "physics",
    stage: "junior",
    group: "运动学",
    title: "匀变速直线运动",
    formula: "v = v₀ + at, s = v₀t + ½at²",
    description: "调节初速度与加速度，观察物体运动状态与 v-t、s-t 图像变化。",
    params: [
      { key: "v0", label: "初速度 v₀", min: 0, max: 30, step: 1, default: 5, unit: "m/s" },
      { key: "a", label: "加速度 a", min: -10, max: 10, step: 0.5, default: 2, unit: "m/s²" },
    ],
    componentKey: "accelerated-motion",
    steps: ["设定初速度 v₀", "加速度 a 产生速度变化", "v = v₀ + at", "s = v₀t + ½at²"],
    hint: "当 a 与 v₀ 同向时加速，反向时减速。",
    animated: true,
    animationDuration: 8,
  },
  // ─── 高中数学 ───
  {
    id: "quadratic-senior",
    subject: "math",
    stage: "senior",
    group: "函数与图像",
    title: "二次函数（高中）",
    formula: "y = ax² + bx + c",
    description: "抛物线的解析式、图像与性质：顶点、对称轴、开口方向。",
    params: [
      { key: "a", label: "a", min: -3, max: 3, step: 0.1, default: 1 },
      { key: "b", label: "b", min: -6, max: 6, step: 0.1, default: 0 },
      { key: "c", label: "c", min: -10, max: 10, step: 0.5, default: 0 },
    ],
    componentKey: "quadratic",
    steps: ["观察抛物线形状", "找对称轴 x = -b/(2a)", "计算顶点", "分析开口方向"],
    hint: "a > 0 开口向上，a < 0 开口向下；|a| 越大开口越窄。",
    animated: true,
    animationDuration: 5,
  },
  {
    id: "exp-log",
    subject: "math",
    stage: "senior",
    group: "函数与图像",
    title: "指数与对数函数",
    formula: "y = aˣ, y = logₐx",
    description: "指数函数与对数函数的图像、性质及其互逆关系。",
    params: [
      { key: "a", label: "底数 a", min: 0.2, max: 5, step: 0.1, default: 2 },
    ],
    componentKey: "exp-log",
    steps: ["画指数函数 y=aˣ", "画对数函数 y=logₐx", "观察关于 y=x 对称", "分析底数对图像的影响"],
    hint: "a > 1 时指数函数递增，0 < a < 1 时递减；两者关于 y=x 对称。",
  },
  {
    id: "vector-dot",
    subject: "math",
    stage: "senior",
    group: "向量",
    title: "向量的数量积",
    formula: "a⃗·b⃗ = |a⃗||b⃗|cosθ",
    description: "两个向量的夹角关系，投影概念的量化表达。",
    params: [
      { key: "ax", label: "a⃗ 的 x 分量", min: -6, max: 6, step: 0.5, default: 4 },
      { key: "ay", label: "a⃗ 的 y 分量", min: -6, max: 6, step: 0.5, default: 2 },
      { key: "bx", label: "b⃗ 的 x 分量", min: -6, max: 6, step: 0.5, default: 3 },
      { key: "by", label: "b⃗ 的 y 分量", min: -6, max: 6, step: 0.5, default: -1 },
    ],
    componentKey: "vector-dot",
    steps: ["确定两个向量", "计算数量积 a⃗·b⃗", "求夹角 θ", "分析投影"],
    hint: "数量积为 0 时两向量垂直；为正时夹角为锐角，为负时为钝角。",
  },
  {
    id: "derivative",
    subject: "math",
    stage: "senior",
    group: "微积分",
    title: "导数的定义",
    formula: "f'(x) = lim[f(x+h)-f(x)]/h",
    description: "函数在某一点瞬时变化率的严格数学定义。",
    params: [
      { key: "a", label: "a (二次项系数)", min: -3, max: 3, step: 0.1, default: 1 },
      { key: "b", label: "b (一次项系数)", min: -6, max: 6, step: 0.1, default: 0 },
      { key: "c", label: "c (常数项)", min: -10, max: 10, step: 0.5, default: 0 },
      { key: "x0", label: "切点 x₀", min: -4, max: 4, step: 0.1, default: 1 },
      { key: "h", label: "邻域 h", min: 0.05, max: 3, step: 0.05, default: 0.5 },
    ],
    componentKey: "derivative",
    steps: ["画函数曲线", "取割线（两点连线）", "让 h→0 割线趋近切线", "切线斜率即导数值"],
    hint: "h 越小，割线越接近切线。当 h→0 时，割线斜率的极限就是导数。",
  },
  {
    id: "coord-3d",
    subject: "math",
    stage: "senior",
    group: "空间几何",
    title: "空间直角坐标系",
    formula: "d = √((x₂-x₁)²+(y₂-y₁)²+(z₂-z₁)²)",
    description: "三维空间中用有序数组 (x,y,z) 表示点的位置。",
    params: [
      { key: "x1", label: "P₁ x", min: -6, max: 6, step: 0.5, default: 3 },
      { key: "y1", label: "P₁ y", min: -6, max: 6, step: 0.5, default: 2 },
      { key: "z1", label: "P₁ z", min: -6, max: 6, step: 0.5, default: 4 },
      { key: "x2", label: "P₂ x", min: -6, max: 6, step: 0.5, default: -2 },
      { key: "y2", label: "P₂ y", min: -6, max: 6, step: 0.5, default: 5 },
      { key: "z2", label: "P₂ z", min: -6, max: 6, step: 0.5, default: 1 },
    ],
    componentKey: "coord-3d",
    steps: ["建立空间直角坐标系", "标出点 P₁", "标出点 P₂", "用距离公式计算"],
    hint: "空间两点距离公式是平面两点距离公式的推广。",
  },
  {
    id: "conic-section",
    subject: "math",
    stage: "senior",
    group: "圆锥曲线",
    title: "椭圆",
    formula: "x²/a² + y²/b² = 1",
    description: "椭圆的定义、标准方程及几何性质。",
    params: [
      { key: "a", label: "半长轴 a", min: 1, max: 10, step: 0.5, default: 5 },
      { key: "b", label: "半短轴 b", min: 0.5, max: 10, step: 0.5, default: 3 },
    ],
    componentKey: "conic-section",
    steps: ["画椭圆曲线", "标出焦点 F₁、F₂", "标出半长轴 a、半短轴 b", "计算焦距 c = √(a²-b²)"],
    hint: "椭圆上任意一点到两焦点的距离之和等于 2a。",
  },
  {
    id: "binomial",
    subject: "math",
    stage: "senior",
    group: "排列组合",
    title: "二项式定理",
    formula: "(a+b)ⁿ = Σ C(n,r)aⁿ⁻ʳbʳ",
    description: "(a+b)ⁿ 展开式的通项公式。",
    params: [
      { key: "n", label: "指数 n", min: 1, max: 10, step: 1, default: 4 },
      { key: "a", label: "a", min: -5, max: 5, step: 0.5, default: 1 },
      { key: "b", label: "b", min: -5, max: 5, step: 0.5, default: 1 },
    ],
    componentKey: "binomial",
    steps: ["写出展开式", "计算各项系数 C(n,r)", "代入 a、b 的值", "验证 (a+b)ⁿ 的结果"],
    hint: "C(n,r) = n! / (r!(n-r)!)，展开式共有 n+1 项。",
  },
  {
    id: "arithmetic-seq",
    subject: "math",
    stage: "senior",
    group: "数列",
    title: "等差数列",
    formula: "aₙ = a₁+(n-1)d, Sₙ = n(a₁+aₙ)/2",
    description: "从函数观点认识等差数列，掌握通项公式与前 n 项和。",
    params: [
      { key: "a1", label: "首项 a₁", min: -10, max: 20, step: 1, default: 2 },
      { key: "d", label: "公差 d", min: -10, max: 10, step: 0.5, default: 3 },
      { key: "n", label: "项数 n", min: 2, max: 20, step: 1, default: 10 },
    ],
    componentKey: "arithmetic-seq",
    steps: ["确定首项 a₁ 和公差 d", "计算各项 aₙ = a₁+(n-1)d", "绘制散点图", "计算前 n 项和 Sₙ"],
    hint: "等差数列的散点图在一条直线上，斜率即为公差 d。",
  },
  {
    id: "geometric-seq",
    subject: "math",
    stage: "senior",
    group: "数列",
    title: "等比数列",
    formula: "aₙ = a₁qⁿ⁻¹, Sₙ = a₁(1-qⁿ)/(1-q)",
    description: "掌握等比数列的通项公式与前 n 项和公式。",
    params: [
      { key: "a1", label: "首项 a₁", min: 0.1, max: 10, step: 0.5, default: 2 },
      { key: "q", label: "公比 q", min: -3, max: 3, step: 0.1, default: 2 },
      { key: "n", label: "项数 n", min: 2, max: 15, step: 1, default: 8 },
    ],
    componentKey: "geometric-seq",
    steps: ["确定首项 a₁ 和公比 q", "计算各项 aₙ = a₁qⁿ⁻¹", "绘制散点图", "计算前 n 项和 Sₙ"],
    hint: "|q| < 1 时数列收敛，|q| > 1 时数列发散，q = 1 时为常数列。",
  },
  {
    id: "complex-number",
    subject: "math",
    stage: "senior",
    group: "复数",
    title: "复数的概念与运算",
    formula: "z = a + bi",
    description: "引入虚数单位 i，将实数系扩充到复数系。",
    params: [
      { key: "a", label: "实部 a", min: -5, max: 5, step: 0.5, default: 3 },
      { key: "b", label: "虚部 b", min: -5, max: 5, step: 0.5, default: 4 },
    ],
    componentKey: "complex-number",
    steps: ["在复平面标出 z", "画向量 OZ", "计算模 |z|", "计算共轭复数 z̄"],
    hint: "|z| = √(a²+b²)，共轭复数 z̄ = a-bi，关于实轴对称。",
  },
  // ─── 高中物理 ───
  {
    id: "momentum",
    subject: "physics",
    stage: "senior",
    group: "力学",
    title: "冲量与动量定理",
    formula: "Δp = F·Δt",
    description: "力对时间的累积效应等于物体动量的变化量。",
    params: [
      { key: "F", label: "力 F", min: 0, max: 50, step: 1, default: 10, unit: "N" },
      { key: "dt", label: "时间 Δt", min: 0.1, max: 10, step: 0.1, default: 2, unit: "s" },
      { key: "m", label: "质量 m", min: 0.5, max: 20, step: 0.5, default: 5, unit: "kg" },
      { key: "v0", label: "初速度 v₀", min: -20, max: 20, step: 1, default: 0, unit: "m/s" },
    ],
    componentKey: "momentum",
    steps: ["确定力 F 和作用时间 Δt", "计算冲量 I = F·Δt", "计算动量变化 Δp = m·Δv", "验证 I = Δp"],
    hint: "动量定理说明力的时间累积改变物体的动量。",
  },
  {
    id: "kinetic-energy",
    subject: "physics",
    stage: "senior",
    group: "力学",
    title: "动能定理",
    formula: "W合 = ½mv² - ½mv₀²",
    description: "合外力对物体所做的功等于物体动能的变化量。",
    params: [
      { key: "F", label: "合外力 F", min: 0, max: 100, step: 1, default: 20, unit: "N" },
      { key: "s", label: "位移 s", min: 0.1, max: 20, step: 0.5, default: 5, unit: "m" },
      { key: "m", label: "质量 m", min: 0.5, max: 20, step: 0.5, default: 2, unit: "kg" },
      { key: "v0", label: "初速度 v₀", min: 0, max: 20, step: 0.5, default: 3, unit: "m/s" },
    ],
    componentKey: "kinetic-energy",
    steps: ["计算合外力做功 W = F·s", "计算初动能 ½mv₀²", "用动能定理求末动能", "求末速度 v"],
    hint: "动能定理适用于变力做功和曲线运动，是能量守恒的体现。",
  },
  {
    id: "mechanical-energy",
    subject: "physics",
    stage: "senior",
    group: "力学",
    title: "机械能守恒定律",
    formula: "Eₖ + Eₚ = 常量",
    description: "只有重力做功时，动能和势能相互转化，总机械能不变。",
    params: [
      { key: "m", label: "质量 m", min: 0.5, max: 20, step: 0.5, default: 2, unit: "kg" },
      { key: "h", label: "高度 h", min: 0, max: 50, step: 0.5, default: 10, unit: "m" },
      { key: "v", label: "速度 v", min: 0, max: 30, step: 0.5, default: 0, unit: "m/s" },
    ],
    componentKey: "mechanical-energy",
    steps: ["计算势能 Eₚ = mgh", "计算动能 Eₖ = ½mv²", "求总机械能 E = Eₖ + Eₚ", "分析能量转化"],
    hint: "只有重力或弹力做功时机械能守恒；有摩擦力时机械能不守恒。",
  },
  {
    id: "gravitation",
    subject: "physics",
    stage: "senior",
    group: "天体",
    title: "万有引力定律",
    formula: "F = GMm/r²",
    description: "任何两个物体之间都存在引力，与质量乘积成正比，与距离平方成反比。",
    params: [
      { key: "M", label: "天体质量 M (×10²⁴kg)", min: 0.1, max: 1000, step: 0.1, default: 5.97, unit: "×10²⁴kg" },
      { key: "m", label: "物体质量 m (×10²²kg)", min: 0.1, max: 100, step: 0.1, default: 7.35, unit: "×10²²kg" },
      { key: "r", label: "距离 r (×10⁸m)", min: 0.1, max: 50, step: 0.1, default: 3.84, unit: "×10⁸m" },
    ],
    componentKey: "gravitation",
    steps: ["确定天体质量和距离", "代入万有引力公式", "计算引力大小", "分析引力与距离的关系"],
    hint: "G = 6.674×10⁻¹¹ N·m²/kg²，万有引力提供天体运动的向心力。",
  },
  {
    id: "coulomb",
    subject: "physics",
    stage: "senior",
    group: "电学",
    title: "库仑定律",
    formula: "F = kQ₁Q₂/r²",
    description: "真空中两个点电荷之间的作用力与电荷量乘积成正比，与距离平方成反比。",
    params: [
      { key: "Q1", label: "电荷 Q₁ (μC)", min: -10, max: 10, step: 0.1, default: 1, unit: "μC" },
      { key: "Q2", label: "电荷 Q₂ (μC)", min: -10, max: 10, step: 0.1, default: -2, unit: "μC" },
      { key: "r", label: "距离 r", min: 0.05, max: 2, step: 0.01, default: 0.3, unit: "m" },
    ],
    componentKey: "coulomb",
    steps: ["确定电荷量和距离", "判断同号/异号电荷", "代入库仑定律计算", "分析力的方向（引力/斥力）"],
    hint: "k = 8.99×10⁹ N·m²/C²；同号电荷相斥，异号电荷相吸。",
  },
  {
    id: "ohm",
    subject: "physics",
    stage: "senior",
    group: "电学",
    title: "欧姆定律",
    formula: "U = IR",
    description: "导体中的电流与电压成正比，与电阻成反比。",
    params: [
      { key: "R", label: "电阻 R", min: 0.5, max: 20, step: 0.5, default: 5, unit: "Ω" },
      { key: "U", label: "电压 U", min: 0, max: 24, step: 0.5, default: 12, unit: "V" },
    ],
    componentKey: "ohm",
    steps: ["确定电阻 R 和电压 U", "用欧姆定律求电流 I = U/R", "在 U-I 图上标出工作点", "分析线性关系"],
    hint: "欧姆定律适用于线性电阻；R = U/I 是电阻的定义式。",
  },
  {
    id: "faraday",
    subject: "physics",
    stage: "senior",
    group: "电磁学",
    title: "法拉第电磁感应定律",
    formula: "E = nΔΦ/Δt",
    description: "感应电动势与磁通量变化率成正比。",
    params: [
      { key: "n", label: "线圈匝数 n", min: 1, max: 1000, step: 1, default: 100 },
      { key: "dPhi", label: "磁通量变化 ΔΦ", min: 0.001, max: 0.5, step: 0.001, default: 0.02, unit: "Wb" },
      { key: "dt", label: "时间变化 Δt", min: 0.01, max: 2, step: 0.01, default: 0.1, unit: "s" },
    ],
    componentKey: "faraday",
    steps: ["确定线圈匝数 n", "测量磁通量变化 ΔΦ", "测量时间变化 Δt", "计算感应电动势 E = nΔΦ/Δt"],
    hint: "磁通量变化越快，感应电动势越大。楞次定律决定感应电流的方向。",
  },
  {
    id: "ac-effective",
    subject: "physics",
    stage: "senior",
    group: "电磁学",
    title: "交流电的有效值",
    formula: "I_eff = I_m/√2",
    description: "交流电有效值等于最大值除以根号2。",
    params: [
      { key: "Im", label: "最大值 I_m", min: 1, max: 50, step: 0.5, default: 10, unit: "A" },
    ],
    componentKey: "ac-effective",
    steps: ["画交流电波形", "标出最大值 I_m", "计算有效值 I_m/√2", "理解热效应等价"],
    hint: "有效值是根据热效应定义的：交流电通过电阻产生的热量与直流电相等。",
  },
  {
    id: "wave",
    subject: "physics",
    stage: "senior",
    group: "波动",
    title: "波速公式",
    formula: "v = λf",
    description: "波速等于波长与频率的乘积。",
    params: [
      { key: "lambda", label: "波长 λ", min: 0.5, max: 20, step: 0.1, default: 4, unit: "m" },
      { key: "f", label: "频率 f", min: 0.1, max: 20, step: 0.1, default: 2, unit: "Hz" },
    ],
    componentKey: "wave",
    steps: ["确定波长 λ 和频率 f", "计算波速 v = λf", "画波形图", "标注波长和振幅"],
    hint: "波速由介质决定，频率由波源决定，波长由两者共同决定。",
  },
  {
    id: "refraction",
    subject: "physics",
    stage: "senior",
    group: "光学",
    title: "折射定律",
    formula: "n₁sinθ₁ = n₂sinθ₂",
    description: "入射角正弦与折射角正弦之比等于折射率之比。",
    params: [
      { key: "n1", label: "折射率 n₁", min: 1, max: 2.5, step: 0.01, default: 1 },
      { key: "n2", label: "折射率 n₂", min: 1, max: 2.5, step: 0.01, default: 1.5 },
      { key: "theta1", label: "入射角 θ₁", min: 0, max: 89, step: 1, default: 30, unit: "°" },
    ],
    componentKey: "refraction",
    steps: ["画入射光线", "确定两介质折射率", "用折射定律求折射角", "判断是否发生全反射"],
    hint: "光从光密介质射向光疏介质时可能发生全反射。",
  },
  // ─── 高中化学 ───
  {
    id: "concentration",
    subject: "chemistry",
    stage: "senior",
    group: "溶液",
    title: "物质的量浓度",
    formula: "c = n/V",
    description: "单位体积溶液中所含溶质的物质的量。",
    params: [
      { key: "nB", label: "溶质的量 n", min: 0.01, max: 5, step: 0.01, default: 0.5, unit: "mol" },
      { key: "V", label: "溶液体积 V", min: 0.01, max: 2, step: 0.01, default: 0.25, unit: "L" },
    ],
    componentKey: "concentration",
    steps: ["确定溶质的物质的量 n", "确定溶液体积 V", "计算浓度 c = n/V", "理解 mol/L 的含义"],
    hint: "物质的量浓度是化学中最常用的浓度表示方法。",
  },
  {
    id: "gas-law",
    subject: "chemistry",
    stage: "senior",
    group: "气体",
    title: "理想气体状态方程",
    formula: "PV = nRT",
    description: "综合了玻意耳定律、查理定律和阿伏伽德罗定律。",
    params: [
      { key: "P", label: "压强 P (Pa)", min: 1000, max: 500000, step: 1000, default: 101325, unit: "Pa" },
      { key: "V", label: "体积 V (m³)", min: 0.001, max: 0.1, step: 0.001, default: 0.0224, unit: "m³" },
      { key: "n", label: "物质的量 n", min: 0.1, max: 10, step: 0.1, default: 1, unit: "mol" },
      { key: "T", label: "温度 T (K)", min: 100, max: 500, step: 1, default: 273.15, unit: "K" },
    ],
    componentKey: "gas-law",
    steps: ["确定气体各参量", "代入 PV=nRT", "验证是否符合理想气体", "分析各参量关系"],
    hint: "R = 8.314 J/(mol·K)，标准状况下 1 mol 理想气体体积约 22.4 L。",
  },
  {
    id: "equilibrium-const",
    subject: "chemistry",
    stage: "senior",
    group: "反应原理",
    title: "化学平衡常数",
    formula: "Kc = [C]^c[D]^d / [A]^a[B]^b",
    description: "一定温度下，平衡时生成物浓度幂之积与反应物浓度幂之积的比值为常数。",
    params: [
      { key: "A0", label: "[A]₀ 初始浓度", min: 0.1, max: 5, step: 0.1, default: 1, unit: "mol/L" },
      { key: "B0", label: "[B]₀ 初始浓度", min: 0.1, max: 5, step: 0.1, default: 1, unit: "mol/L" },
      { key: "K", label: "平衡常数 K", min: 0.01, max: 100, step: 0.01, default: 2 },
    ],
    componentKey: "equilibrium-const",
    steps: ["写出反应方程式", "设反应进度 x", "列平衡常数表达式", "求解平衡浓度"],
    hint: "K 只与温度有关，与浓度无关。K > 1 正反应占优势，K < 1 逆反应占优势。",
  },
  {
    id: "ka",
    subject: "chemistry",
    stage: "senior",
    group: "电离平衡",
    title: "电离平衡常数",
    formula: "Ka = [H⁺][A⁻]/[HA]",
    description: "衡量弱电解质在水溶液中电离程度的常数。",
    params: [
      { key: "Ka", label: "Ka", min: 1e-8, max: 1e-2, step: 1e-8, default: 1.8e-5 },
      { key: "C0", label: "初始浓度 C₀", min: 0.001, max: 2, step: 0.001, default: 0.1, unit: "mol/L" },
    ],
    componentKey: "ka",
    steps: ["写出弱酸电离方程式", "设电离度 α", "列 Ka 表达式", "求 [H⁺] 和 pH"],
    hint: "Ka 越大，弱酸酸性越强。多元弱酸分步电离，Ka₁ >> Ka₂。",
  },
  {
    id: "kw",
    subject: "chemistry",
    stage: "senior",
    group: "电离平衡",
    title: "水的离子积常数",
    formula: "Kw = [H⁺][OH⁻] = 10⁻¹⁴",
    description: "一定温度下，水中氢离子和氢氧根离子浓度的乘积为常数。",
    params: [
      { key: "H", label: "[H⁺] 浓度", min: 1e-14, max: 1, step: 1e-8, default: 1e-7, unit: "mol/L" },
    ],
    componentKey: "kw",
    steps: ["给定 [H⁺]", "用 Kw 求 [OH⁻]", "计算 pH", "判断酸碱性"],
    hint: "25°C 时 Kw = 10⁻¹⁴。pH + pOH = 14。温度升高 Kw 增大。",
  },
  {
    id: "ksp",
    subject: "chemistry",
    stage: "senior",
    group: "沉淀平衡",
    title: "溶度积常数",
    formula: "Ksp = [Aᵐ⁺]ⁿ[Bⁿ⁻]ᵐ",
    description: "难溶电解质饱和溶液中离子浓度幂的乘积为常数。",
    params: [
      { key: "Ksp", label: "Ksp", min: 1e-15, max: 1e-2, step: 1e-15, default: 1.8e-10 },
    ],
    componentKey: "ksp",
    steps: ["写出溶解平衡方程式", "设溶解度 s", "列 Ksp 表达式", "求溶解度"],
    hint: "Ksp 越小，难溶电解质越难溶。离子积 > Ksp 时产生沉淀。",
  },
  {
    id: "titration",
    subject: "chemistry",
    stage: "senior",
    group: "定量分析",
    title: "滴定反应计算",
    formula: "C₁V₁n₁ = C₂V₂n₂",
    description: "用已知浓度的标准溶液测定未知浓度的待测液。",
    params: [
      { key: "Ca", label: "酸浓度 Cₐ", min: 0.001, max: 2, step: 0.001, default: 0.1, unit: "mol/L" },
      { key: "Va", label: "酸体积 Vₐ", min: 1, max: 100, step: 0.5, default: 25, unit: "mL" },
      { key: "Cb", label: "碱浓度 Cᵦ", min: 0.001, max: 2, step: 0.001, default: 0.1, unit: "mol/L" },
      { key: "Vb", label: "碱体积 Vᵦ", min: 1, max: 100, step: 0.5, default: 25, unit: "mL" },
      { key: "n_acid", label: "酸的化学计量数", min: 1, max: 3, step: 1, default: 1 },
      { key: "n_base", label: "碱的化学计量数", min: 1, max: 3, step: 1, default: 1 },
    ],
    componentKey: "titration",
    steps: ["确定酸碱浓度和体积", "写出反应方程式", "用 C₁V₁n₁=C₂V₂n₂ 计算", "判断是否恰好中和"],
    hint: "一元酸碱中和时 CₐVₐ=CᵦVᵦ。滴定终点用指示剂判断。",
  },
  // ─── 小学数学 ───
  {
    id: "fraction",
    subject: "math",
    stage: "primary",
    group: "数与运算",
    title: "分数的意义",
    formula: "a/b",
    description: "用圆形图理解分数的意义与等值分数。",
    params: [
      { key: "a", label: "分子 a", min: 1, max: 11, step: 1, default: 1 },
      { key: "b", label: "分母 b", min: 2, max: 12, step: 1, default: 3 },
      { key: "k", label: "扩大倍数 k", min: 1, max: 5, step: 1, default: 2 },
    ],
    componentKey: "fraction",
    steps: ["将整体分成 b 份", "取其中 a 份", "分子分母同乘 k", "验证等值分数"],
    hint: "分数的分子分母同时乘以或除以同一个非零数，分数值不变。",
  },
  {
    id: "area",
    subject: "math",
    stage: "primary",
    group: "图形与几何",
    title: "平面图形面积",
    formula: "S = 底 × 高, S = ½ × 底 × 高",
    description: "矩形和三角形面积公式的直观展示。",
    params: [
      { key: "shape", label: "形状 (0:矩形 1:三角形)", min: 0, max: 1, step: 1, default: 0 },
      { key: "base", label: "底边长", min: 1, max: 12, step: 0.5, default: 6 },
      { key: "height", label: "高", min: 1, max: 10, step: 0.5, default: 4 },
    ],
    componentKey: "area",
    steps: ["选择形状", "确定底和高", "代入面积公式", "计算面积"],
    hint: "三角形面积是同底等高矩形面积的一半。",
  },
  {
    id: "ratio",
    subject: "math",
    stage: "primary",
    group: "比与比例",
    title: "比与比例",
    formula: "a/b = c/d → ad = bc",
    description: "比的概念与比例的基本性质。",
    params: [
      { key: "a", label: "比的前项 a", min: 1, max: 20, step: 1, default: 2 },
      { key: "b", label: "比的后项 b", min: 1, max: 20, step: 1, default: 3 },
      { key: "k", label: "扩大倍数 k", min: 1, max: 5, step: 1, default: 2 },
    ],
    componentKey: "ratio",
    steps: ["写出比 a:b", "同时乘以 k 得到等值比", "验证 ad = bc", "理解比例的基本性质"],
    hint: "比例的基本性质：两个外项之积等于两个内项之积。",
  },
  {
    id: "simple-equation",
    subject: "math",
    stage: "primary",
    group: "方程",
    title: "简易方程",
    formula: "ax + b = c",
    description: "用天平模型理解方程的解法。",
    params: [
      { key: "a", label: "a 系数", min: 1, max: 10, step: 1, default: 2 },
      { key: "b", label: "b 常数", min: 0, max: 20, step: 1, default: 3 },
      { key: "c", label: "c 右边", min: 1, max: 30, step: 1, default: 7 },
    ],
    componentKey: "simple-equation",
    steps: ["写出方程 ax+b=c", "移项: ax = c-b", "两边除以 a", "得到 x 的值"],
    hint: "方程两边同时加上或减去同一个数，等式仍然成立。",
  },
  {
    id: "coord",
    subject: "math",
    stage: "primary",
    group: "图形与几何",
    title: "坐标系与位置",
    formula: "(x, y)",
    description: "在坐标系中确定点的位置。",
    params: [
      { key: "x", label: "x 坐标", min: -8, max: 8, step: 1, default: 3 },
      { key: "y", label: "y 坐标", min: -8, max: 8, step: 1, default: 2 },
    ],
    componentKey: "coord",
    steps: ["建立坐标系", "沿 x 轴找到 x 值", "沿 y 轴找到 y 值", "标出点 (x,y)"],
    hint: "x 表示水平方向的位置，y 表示竖直方向的位置。",
  },
  // ─── 小学科学 ───
  {
    id: "matter-states",
    subject: "chemistry",
    stage: "primary",
    group: "物质变化",
    title: "物质三态变化",
    formula: "固态 ⇌ 液态 ⇌ 气态",
    description: "通过温度变化观察物质在固态、液态、气态之间的转换。",
    params: [
      { key: "temp", label: "温度", min: 0, max: 100, step: 1, default: 50, unit: "°C" },
    ],
    componentKey: "matter-states",
    steps: ["观察低温下粒子排列", "升温观察状态变化", "理解三态特征", "总结转化规律"],
    hint: "固态粒子紧密排列，液态可流动，气态自由运动。温度是影响状态变化的关键因素。",
  },
  // ─── 初中数学 ───
  {
    id: "absolute-value",
    subject: "math",
    stage: "junior",
    group: "实数",
    title: "实数与绝对值",
    formula: "|x| = 距离原点的距离",
    description: "绝对值的几何意义是数轴上点到原点的距离。",
    params: [
      { key: "x", label: "x 的值", min: -12, max: 12, step: 0.5, default: 3 },
    ],
    componentKey: "absolute-value",
    steps: ["在数轴上标出 x", "找到原点", "测量 x 到原点的距离", "理解 |x| 的含义"],
    hint: "|x| 永远大于等于 0。当 x ≥ 0 时 |x| = x，当 x < 0 时 |x| = -x。",
  },
  {
    id: "linear-system",
    subject: "math",
    stage: "junior",
    group: "方程与不等式",
    title: "二元一次方程组",
    formula: "a₁x + b₁y = c₁, a₂x + b₂y = c₂",
    description: "两条直线的交点就是方程组的解。",
    params: [
      { key: "a1", label: "方程1 a₁", min: -5, max: 5, step: 1, default: 2 },
      { key: "b1", label: "方程1 b₁", min: -5, max: 5, step: 1, default: 1 },
      { key: "c1", label: "方程1 c₁", min: -10, max: 10, step: 1, default: 5 },
      { key: "a2", label: "方程2 a₂", min: -5, max: 5, step: 1, default: 1 },
      { key: "b2", label: "方程2 b₂", min: -5, max: 5, step: 1, default: -1 },
      { key: "c2", label: "方程2 c₂", min: -10, max: 10, step: 1, default: 1 },
    ],
    componentKey: "linear-system",
    steps: ["画出两条直线", "找交点坐标", "验证解的正确性", "理解唯一解的条件"],
    hint: "两直线相交有唯一解，平行无解，重合有无穷多解。",
  },
  {
    id: "inequality",
    subject: "math",
    stage: "junior",
    group: "方程与不等式",
    title: "一元一次不等式",
    formula: "ax + b > 0",
    description: "在数轴上表示不等式的解集。",
    params: [
      { key: "a", label: "a 系数", min: -5, max: 5, step: 0.5, default: 2 },
      { key: "b", label: "b 常数", min: -10, max: 10, step: 0.5, default: -4 },
    ],
    componentKey: "inequality",
    steps: ["解方程 ax+b=0 得边界点", "判断 a 的正负", "确定解集方向", "在数轴上表示"],
    hint: "a > 0 时解集在边界点右侧，a < 0 时在左侧。",
  },
  {
    id: "pythagorean",
    subject: "math",
    stage: "junior",
    group: "三角形",
    title: "勾股定理",
    formula: "a² + b² = c²",
    description: "直角三角形三边的关系。",
    params: [
      { key: "a", label: "直角边 a", min: 1, max: 15, step: 0.5, default: 3 },
      { key: "b", label: "直角边 b", min: 1, max: 15, step: 0.5, default: 4 },
    ],
    componentKey: "pythagorean",
    steps: ["画直角三角形", "在各边构造正方形", "计算面积", "验证 a²+b²=c²"],
    hint: "勾股定理只适用于直角三角形。常见的勾股数：3-4-5, 5-12-13, 8-15-17。",
  },
  {
    id: "similar",
    subject: "math",
    stage: "junior",
    group: "图形变换",
    title: "相似与位似",
    formula: "相似比 k",
    description: "通过位似变换理解相似图形的关系。",
    params: [
      { key: "k", label: "相似比 k", min: 0.2, max: 3, step: 0.1, default: 2 },
    ],
    componentKey: "similar",
    steps: ["确定位似中心", "按比例 k 缩放", "观察对应边之比", "观察面积之比"],
    hint: "对应边之比 = k，面积之比 = k²。",
  },
  {
    id: "circle",
    subject: "math",
    stage: "junior",
    group: "圆",
    title: "圆的性质",
    formula: "圆心角 = 2 × 圆周角",
    description: "圆心角与圆周角的关系。",
    params: [
      { key: "r", label: "半径 r", min: 3, max: 10, step: 0.5, default: 6 },
    ],
    componentKey: "circle",
    steps: ["画圆和圆心", "确定圆上的点", "测量圆心角", "测量圆周角"],
    hint: "同弧上的圆周角等于圆心角的一半。",
  },
  {
    id: "probability",
    subject: "math",
    stage: "junior",
    group: "统计与概率",
    title: "概率与频率",
    formula: "P(A) = m/n",
    description: "通过模拟实验理解频率趋近于概率。",
    params: [
      { key: "sides", label: "骰子面数", min: 2, max: 20, step: 1, default: 6 },
      { key: "target", label: "目标面", min: 1, max: 20, step: 1, default: 1 },
      { key: "trials", label: "试验次数", min: 10, max: 1000, step: 10, default: 100 },
    ],
    componentKey: "probability",
    steps: ["确定骰子面数和目标面", "计算理论概率", "模拟多次试验", "观察频率趋近概率"],
    hint: "试验次数越多，频率越趋近于理论概率。这就是大数定律。",
  },
  // ─── 初中物理 ───
  {
    id: "density",
    subject: "physics",
    stage: "junior",
    group: "物质属性",
    title: "密度",
    formula: "ρ = m / V",
    description: "单位体积的某种物质的质量。",
    params: [
      { key: "m", label: "质量 m", min: 1, max: 500, step: 1, default: 270, unit: "g" },
      { key: "V", label: "体积 V", min: 1, max: 500, step: 1, default: 100, unit: "cm³" },
    ],
    componentKey: "density",
    steps: ["测量物体质量", "测量物体体积", "计算密度 ρ=m/V", "查密度表判断物质"],
    hint: "密度是物质的特性，不随质量和体积改变。水的密度为 1 g/cm³。",
  },
  {
    id: "pressure",
    subject: "physics",
    stage: "junior",
    group: "压强",
    title: "压强与液体压强",
    formula: "p = F/S, p = ρgh",
    description: "固体压强与液体压强的计算。",
    params: [
      { key: "F", label: "压力 F", min: 1, max: 500, step: 1, default: 100, unit: "N" },
      { key: "S", label: "受力面积 S", min: 0.01, max: 2, step: 0.01, default: 0.5, unit: "m²" },
      { key: "rho", label: "液体密度 ρ", min: 500, max: 2000, step: 10, default: 1000, unit: "kg/m³" },
      { key: "h", label: "深度 h", min: 0.1, max: 20, step: 0.1, default: 5, unit: "m" },
    ],
    componentKey: "pressure",
    steps: ["计算固体压强 p=F/S", "计算液体压强 p=ρgh", "理解两者的区别", "比较数值大小"],
    hint: "固体压强与受力面积有关；液体压强只与深度和密度有关。",
  },
  {
    id: "buoyancy",
    subject: "physics",
    stage: "junior",
    group: "浮力",
    title: "浮力",
    formula: "F浮 = ρ液·g·V排",
    description: "浸在液体中的物体受到向上的浮力。",
    params: [
      { key: "rhoLiquid", label: "液体密度 ρ", min: 500, max: 2000, step: 10, default: 1000, unit: "kg/m³" },
      { key: "V", label: "排开体积 V排", min: 0.001, max: 0.1, step: 0.001, default: 0.01, unit: "m³" },
      { key: "m", label: "物体质量 m", min: 0.1, max: 50, step: 0.1, default: 8, unit: "kg" },
    ],
    componentKey: "buoyancy",
    steps: ["计算浮力 F浮=ρ液gV排", "计算重力 G=mg", "比较浮力和重力", "判断上浮或下沉"],
    hint: "F浮 > G 时上浮，F浮 < G 时下沉，F浮 = G 时悬浮。",
  },
  {
    id: "lever",
    subject: "physics",
    stage: "junior",
    group: "简单机械",
    title: "杠杆平衡",
    formula: "F₁·d₁ = F₂·d₂",
    description: "杠杆平衡的条件：动力×动力臂 = 阻力×阻力臂。",
    params: [
      { key: "F1", label: "动力 F₁", min: 1, max: 100, step: 1, default: 20, unit: "N" },
      { key: "d1", label: "动力臂 d₁", min: 0.5, max: 5, step: 0.1, default: 2, unit: "m" },
      { key: "F2", label: "阻力 F₂", min: 1, max: 100, step: 1, default: 10, unit: "N" },
      { key: "d2", label: "阻力臂 d₂", min: 0.5, max: 5, step: 0.1, default: 4, unit: "m" },
    ],
    componentKey: "lever",
    steps: ["确定动力和动力臂", "确定阻力和阻力臂", "计算力矩", "判断是否平衡"],
    hint: "力臂是从支点到力的作用线的垂直距离。",
  },
  {
    id: "electric-power",
    subject: "physics",
    stage: "junior",
    group: "电学",
    title: "电功与电功率",
    formula: "W = UIt, P = UI",
    description: "电流做功与电功率的计算。",
    params: [
      { key: "U", label: "电压 U", min: 1, max: 380, step: 1, default: 220, unit: "V" },
      { key: "I", label: "电流 I", min: 0.01, max: 10, step: 0.01, default: 0.5, unit: "A" },
      { key: "t", label: "时间 t", min: 1, max: 3600, step: 1, default: 60, unit: "s" },
    ],
    componentKey: "electric-power",
    steps: ["确定电压和电流", "计算电功率 P=UI", "计算电功 W=UIt", "换算为 kWh"],
    hint: "1 kWh = 3.6×10⁶ J，俗称 1 度电。",
  },
  // ─── 初中化学 ───
  {
    id: "mass-conservation",
    subject: "chemistry",
    stage: "junior",
    group: "化学反应",
    title: "质量守恒定律",
    formula: "反应前后质量不变",
    description: "参加化学反应的各物质质量总和等于反应后各物质质量总和。",
    params: [
      { key: "nA", label: "反应物A系数", min: 1, max: 5, step: 1, default: 2 },
      { key: "nB", label: "反应物B系数", min: 1, max: 5, step: 1, default: 1 },
      { key: "mA", label: "A的摩尔质量", min: 1, max: 100, step: 1, default: 2, unit: "g/mol" },
      { key: "mB", label: "B的摩尔质量", min: 1, max: 100, step: 1, default: 32, unit: "g/mol" },
      { key: "mC", label: "C的摩尔质量", min: 1, max: 100, step: 1, default: 18, unit: "g/mol" },
    ],
    componentKey: "mass-conservation",
    steps: ["写出反应方程式", "计算反应前总质量", "计算反应后总质量", "验证质量守恒"],
    hint: "质量守恒的本质：化学反应前后原子种类和数目不变。",
  },
  {
    id: "mass-fraction",
    subject: "chemistry",
    stage: "junior",
    group: "溶液",
    title: "溶液质量分数",
    formula: "ω = 溶质质量 / 溶液质量 × 100%",
    description: "溶质质量占溶液质量的百分比。",
    params: [
      { key: "solute", label: "溶质质量", min: 1, max: 100, step: 1, default: 20, unit: "g" },
      { key: "solvent", label: "溶剂质量", min: 1, max: 500, step: 1, default: 80, unit: "g" },
    ],
    componentKey: "mass-fraction",
    steps: ["确定溶质质量", "确定溶剂质量", "计算溶液质量", "计算质量分数"],
    hint: "溶液质量 = 溶质质量 + 溶剂质量。饱和溶液的质量分数最大。",
  },
  {
    id: "acid-base-ph",
    subject: "chemistry",
    stage: "junior",
    group: "酸碱盐",
    title: "酸碱与pH",
    formula: "pH = -lg[H⁺]",
    description: "用pH表示溶液的酸碱性强弱。",
    params: [
      { key: "pH", label: "pH值", min: 0, max: 14, step: 0.1, default: 7 },
    ],
    componentKey: "acid-base-ph",
    steps: ["理解pH的含义", "在pH标尺上定位", "判断酸碱性", "了解常见物质的pH"],
    hint: "pH < 7 为酸性，pH = 7 为中性，pH > 7 为碱性。",
  },
];

/** 获取指定学科+学段下的所有主题 */
export function topicsFor(subject: Subject, stage: Stage): Topic[] {
  return TOPICS.filter((topic) => topic.subject === subject && topic.stage === stage);
}

/** 根据 id 获取单个主题 */
export function getTopic(id: string): Topic | undefined {
  return TOPICS.find((topic) => topic.id === id);
}

/** 判断指定学科+学段下是否有主题内容 */
export function hasTopicsFor(subject: Subject, stage: Stage): boolean {
  return TOPICS.some((topic) => topic.subject === subject && topic.stage === stage);
}
